name: Building GSI..

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://s252vla.storage.yandex.net/rdisk/270edf5ad652e07101d8dbea783c48715f86eebe22def355bc8b7e4d67938c5e/5f974375/Av7yVleztnw7sFG-Vu0QQyep5DCZ8Al75NyTkEqmf4p9jZpmRtAcCEclpT5tVZf93OicGPUvkfufYWhrdgNJoQ==?uid=0&filename=MIUITR_20.10.1_MI9TPRO_RAPHAEL_M12-A10.zip&disposition=attachment&hash=pFFB4wyMpZWGUteN0rIT5U5LbaWYqumCbR7kMVMuSbj8CTL5NM716Y%2BPUcFfOxDgq/J6bpmRyOJonT3VoXnDag%3D%3D&limit=0&content_type=application%2Fzip&owner_uid=226448624&fsize=2199050168&hid=f2d8fb5dab8e46d066bd8dd3fa0c063d&media_type=compressed&tknv=v2&rtoken=ld3K6fv1WUyD&force_default=no&ycrid=na-83ed7dbfc7598d2b9ffb4c9de1b88964-downloader16e&ts=5b299d9100740&s=1e7504a911ffd3eb05eb1f93b704b2759e716940e55349d9c89d83ae3fbd8801&pb=U2FsdGVkX1_Ls11cla4mZ2cI4iQ-iC-JhbsYn97txpePof5ARvTIVoRBAXbhlAzMXqNPXHObhmxOy1fifndz7sl-537uw1oNk-mD2kRltIg
  ROM_NAME: MIUI
  ZIP_NAME: MIUITR_RAPHAEL_20.10.01_BiberGSI
  TZ: Asia/Kolkata
  MIR: wet
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Clean Up
         run: |
           docker rmi `docker images -q`
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
           sudo -E apt-get update
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean 
           
       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget

       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: sudo ./ErfanGSIs/url2GSI.sh $ROM_URL $ROM_NAME
       
       - name: Zip Aonly and upload 
         run: |
              mkdir final
              sudo chmod -R 777 ErfanGSIs/output
              cd ErfanGSIs/output
              zip -r $ZIP_NAME-GSI-Aonly-ProjectTrebleRom.7z *-Aonly-*.img
              touch links.txt
              curl -sL https://git.io/file-transfer | sh
              echo "Aonly : " >> links.txt
              ./transfer $MIR $ZIP_NAME-GSI-Aonly-ProjectTrebleRom.7z  | grep Download >> links.txt       
       - name: Zip AB and upload 
         run: |
              cd ErfanGSIs/output
              zip -r $ZIP_NAME-GSI-AB-ProjectTrebleRom.7z *-AB-*.img
              ./transfer $MIR $ZIP_NAME-GSI-AB-ProjectTrebleRom.7z | grep Download >> links.txt   
              
       - name: Print download links
         run: |
              cd ErfanGSIs/output
              cat links.txt
              
       - name: Print build info
         run: |
              cat ErfanGSIs/output/*-Aonly-*.txt
         
            
