name: Building GSI..

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://dllb2.pling.com/api/files/download/j/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjE2MDIwNzYwMTYiLCJ1IjpudWxsLCJsdCI6ImRvd25sb2FkIiwicyI6IjRhN2U0YzVhN2ZmYzQxNmZjOWRiM2MzNDNmZGExYTY0YTU4M2QwNjgzYTkzYjE3OWQ2OWRlNmM0Y2JkMzI1NTdhMWUwYWI1YmY0MjJlYzc5MzE0YzU5ZjUwNzdkZjA4Y2VmMDFjNmQ2ZmUyZDlhMmFjZWUwNzIyOWFkODlkYzE2IiwidCI6MTYwMjYxNjI3MSwic3RmcCI6IjI4ZDBjMzFhYmI4NGI2ZDAwNWMzMTg4ODRmMjQ0ODUwIiwic3RpcCI6Ijk1LjEyLjExNC4xNjgifQ.MxiokolsxtN1MSHPzWrNr8G8pu29fS7QGrV6hsfR404/ExtendedUI-2.0-R-OFFICIAL-ginkgo-20201007-0845.zip
  ROM_NAME: Generic
  ZIP_NAME: ExtendedUI-2.0-R
  TZ: Asia/Kolkata
  MIR: wet
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Clean Up
         run: |
           docker rmi `docker images -q`
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
           sudo -E apt-get update
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean 
           
       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget

       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: sudo ./ErfanGSIs/url2GSI.sh $ROM_URL $ROM_NAME
       
       - name: Zip Aonly and upload 
         run: |
              mkdir final
              sudo chmod -R 777 ErfanGSIs/output
              cd ErfanGSIs/output
              zip -r $ZIP_NAME-GSI-Aonly.7z *-Aonly-*.img
              touch links.txt
              curl -sL https://git.io/file-transfer | sh
              echo "Aonly : " >> links.txt
              ./transfer $MIR $ZIP_NAME-GSI-Aonly.7z  | grep Download >> links.txt       
       - name: Zip AB and upload 
         run: |
              cd ErfanGSIs/output
              zip -r $ZIP_NAME-GSI-AB.7z *-AB-*.img
              ./transfer $MIR $ZIP_NAME-GSI-AB.7z | grep Download >> links.txt   
              
       - name: Print download links
         run: |
              cd ErfanGSIs/output
              cat links.txt
              
       - name: Print build info
         run: |
              cat ErfanGSIs/output/*-Aonly-*.txt
         
            
